<?php if(extension_loaded('zlib')){ob_start('ob_gzhandler');} header("Content-type: text/javascript"); ?>
(function(){var E,J,K,w=(navigator.userAgent||navigator.vendor||window.opera).toLowerCase();/mozilla/.test(w)&&/webkit/.test(w);E=/webkit/.test(w);/opera/.test(w);/msie/.test(w);J=w.match(/ipad/i)||w.match(/iphone/i)||w.match(/ipod/i);K=w.match(/android/i);"undefined"===typeof pageID&&(pageID="all");var e={tryMobile:function(){J&&e.$body.addClass("mobile").addClass("mobile-ios");K&&e.$body.addClass("mobile").addClass("mobile-android")},header:function(){var f=$("#site-navigation"),g=$(".aside-sidebar"),
d=!1,a=!1,h=e.$scroll.scrollTop(),l=e.$scroll.scrollTop()-10,b=!1,c=function(){h=e.$scroll.scrollTop();l<h?(a&&(a=!1,f.removeClass("open"),g.addClass("close")),70<h&&!d&&(d=!0,f.addClass("fixed"),setTimeout(function(){f.addClass("animated")},50)),70<h&&!b&&(b=!0,f.addClass("disableMenu"))):l>h&&(a||(a=!0,f.addClass("open"),g.removeClass("close")),2>h&&d&&(d=!1,f.removeClass("fixed").removeClass("animated")),b&&(b=!1,f.removeClass("disableMenu")));l=h};70<h&&g.addClass("close");c();e.$window.scroll(c)},
contentSlider:function(){$(".content .slider").each(function(){var f=$(this).addClass("rendered"),g=f.find("img"),d=g.length,a=-1,h=0,l=$('<div class="slider-content"></div>'),b=$('<div class="slider-controls"></div>'),c=$(),p=!1,k=$('<div class="slider-arrow to-left"><span></span></div>'),v=$('<div class="slider-arrow to-right"><span></span></div>'),r=function(){l.css("height",g.eq(a).height()+"px")},y=function(b,k){b==a||p||(k&&null!=u&&(clearInterval(u),u=null),p=!0,0>b&&(b=d-1),b>=d&&(b=0),h=
a,a=b,g.eq(a).addClass("current"),g.eq(h).removeClass("current").addClass("post-current"),c.eq(a).addClass("current"),c.eq(h).removeClass("current"),r(),setTimeout(function(){g.removeClass("post-current");p=!1},790))},u=setInterval(function(){y(a+1,!1)},7E3);f.html("").append(l.append(g)).append(b).append(k).append(v);for(f=0;f<d;f++)$('<span title="'+g.eq(f).attr("alt")+'" data-ind="'+f+'"></span>').appendTo(b).click(function(){y(parseInt($(this).attr("data-ind")),!0)});c=b.find("span");k.click(function(){y(a-
1,!0)});v.click(function(){y(a+1,!0)});y(0);e.$window.resize(r)})},waitImgsForLoad:function(f,e,d){var a=d||!1;f=$(f);var h=f.length,l=0,b=!1,c=function(){l++;l>=h&&!b&&(b=!0,e())};0<h?f.each(function(){var b=$(this);b[0].complete?c():(b.load(function(){c()}),a||b.error(c))}):e()},nicescroll:function(){$.fn.niceScroll?e.$html.niceScroll({cursoropacitymin:.5,cursorcolor:"#999",cursorborder:"none",cursorborderradius:"1px",cursorfixedheight:100}):e.$html.css("overflow","auto")},home:function(){e.$html.scrollTop(0);
var f=846/476,g=$("#home-presentation"),d=$("#home-presentation-content"),a=$("#home-presentation-videocontainer"),h=$("#home-presentation-text"),l=$("#home-presentation-text-wrap"),b=1E3,c=function(){b=e.$window.height()-65;g.height(b);var k=g.width(),c="100%",d="0";k/b<f&&(d=b*f,c=d+"px",d=-.5*(d-k)+"px");a.css({width:c,left:d});k=l.height();h.css({top:.5*(b-k)+"px"})},p=function(){var a=.5*(e.$scroll.scrollTop()-60),a=a>b?b:a;d.css("top",a+"px")};c();p();e.$window.resize(c).scroll(p);l.animate({opacity:1},
600);$("#goto-last-work").click(function(a){a.preventDefault();a=$(this).attr("href");a=$(a).offset().top;$("html,body").animate({scrollTop:a+"px"},800)})},illustrationList:function(){var f=4,g="all",d=!0,a=$(".gallery").not(".gridding").addClass("gridding"),h=a.find("figure"),l=$(".gallery-menu a"),b=function(){var b=e.$window.width();f=4;1400>b&&(f=3);820>b&&(f=2);500>b&&(f=1);var c=0,d=0,g=100/f,l=Math.round(a.width()/f);h.not(".hidden").each(function(){$(this).css({width:g+"%",height:l+"px",left:c+
"%",top:d+"px"});c+=g;100<=c&&(c=0,d+=l)});a.height(d+l)},c=function(a,c){a!=g&&d&&(d=!1,"all"==a?h.removeClass("hidden"):"all"==g?h.not("."+a).addClass("hidden"):(h.filter("."+g).addClass("hidden"),h.filter("."+a).removeClass("hidden")),g=a,setTimeout(function(){d=!0},600),l.parent().removeClass("current"),c.parent().addClass("current"));b()};(function(){var a=$(".illustration-thumb-img"),b=a.length,c=0,d=function(){if(c<b){var d=a.eq(c),f=d.attr("srcwait");d.attr("src",f)}},f=function(a){null!==
a&&a.css("opacity","1");++c;d()};a.load(function(){f($(this))}).error(function(){f(null)});d()})();b();e.$window.resize(b);l.click(function(a){a.preventDefault();a=$(this);var b=a.text().toLowerCase().replace(/ /g,"-");-1!=b.indexOf("all-")&&(b="all");c(b,a)})},illustrationPost:function(){e.$html.scrollTop(0);$(".post-navigation").addClass("visible");var f=$(".illustration-post-large-image figure"),g=f.find("img").eq(0),d=$(".illustration-post .summary"),a=$(".summary-content-col"),h=5E3,l=e.$window.height(),
b=!1,c=function(){var b=1,c=e.$scroll.scrollTop();80>=c?b=1:80<c&&300>=c?b=1-(c-80)/220:300<c&&(b=0);a.css("opacity",b);300<c&&(b=c-300,c=h-l,b>c&&(b=0<c?c:0),f.css("top",-b+"px"))},p=function(){l=e.$window.height();h=b?g.height():l;d.height(h+300-50)},k=null;(function(){var a=$("#scroll-down"),b=6,c=!1;k=setInterval(function(){b--;0==b&&(a.fadeIn(400),c=!0)},1E3);e.$window.scroll(function(){c&&(a.fadeOut(400),b=10,c=!1)});return this})();p();c();g[0].complete?(b=!0,p(),c()):g.load(function(){b=!0;
p();c()});e.$window.resize(function(){p();c()}).scroll(function(){c();k&&(clearInterval(k),k=null)});var v=$(".wipSlider");0<v.length&&$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){v.wipSlider()});var r=!1;$("pre").not(".no-print").each(function(){var a=$(this).addClass("prettyprint");a.text(a.html());r=!0});r&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");e.socialComments(".illustration-post-large-image img,.content img");
e.commentValidation()},blogList:function(){},blogPost:function(){var f=$(".wipSlider");0<f.length&&$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){f.wipSlider()});var g=!1;$("pre").not(".no-print").each(function(){var d=$(this).addClass("prettyprint");d.text(d.html());g=!0});g&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");e.socialComments(".content img");e.commentValidation()},designPost:function(){var f=$(".wipSlider");0<f.length&&
$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){f.wipSlider()});var g=!1;$("pre").not(".no-print").each(function(){var d=$(this).addClass("prettyprint");d.text(d.html());g=!0});g&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");e.socialComments(".content img");e.commentValidation()},socialComments:function(f){var g=$("#comment-tabs"),d=function(){var a=window.comment_tab_width||750,d=window.location.href;$("#gplus-tab").html('<div class="g-comments" data-width="'+
a+'" data-href="'+d+'" data-first_party_property="BLOGGER" data-view_type="FILTERED_POSTMOD">Loading Google+ Comments ...</div>');$("#fb-comments").html('<div class="fb-comments" data-width="'+a+'" data-href="'+d+'" data-num-posts="20" data-colorscheme="light" data-mobile="auto"></div>')},a=function(){$.getScript("//apis.google.com/js/plusone.js?callback=gpcb");$.getScript("//connect.facebook.net/en_US/all.js#xfbml=1",function(){FB.init();FB.XFBML.parse()})};0<g.length&&(function(){g.each(function(){var a=
$(this),d=a.find(".controls"),b=d.find("a"),c=a.find(".content-tab"),f="",e=function(a){var e=a.attr("href");e!=f&&(f=e,b.parent().removeClass("active"),a.parent().addClass("active"),d.removeClass("gplus-tab facebook-tab wordpress-tab").addClass(f.substr(1)),c.hide(),$(f).show())};e(b.eq(0));b.click(function(a){a.preventDefault();e($(this))})})}(),d(),e.waitImgsForLoad(f||"",function(){setTimeout(function(){a()},50)}))},commentValidation:function(){var f=$("#commentform");$("#statusMessage").html("");
var e=f.find("fieldset.validate");e.find("input,textarea").val("");var d=f.find("input[type=text],input[type=email],textarea").removeAttr("disabled"),a=$("#adding-comment"),h=$("#adding-comment-error"),l=$("#commentlist"),b=$("#commentlist-title"),c=l.find(">li").length,p=function(){var a=!0;e.each(function(){var b=$(this).removeClass("error"),c=b.find("input,textarea");b.attr("data-min");var d=c.val();3>d.length?(a=!1,b.addClass("error"),c.focus()):b.hasClass("email")&&-1==d.search(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i)&&
(a=!1,b.addClass("error"),c.focus())});return a},k=function(){var e=f.serialize(),g=f.attr("action");d.attr("disabled","true");h.hide();a.fadeIn(300,function(){$.ajax({type:"post",url:g,data:e,error:function(){a.hide();h.show();d.removeAttr("disabled")},success:function(e){$(e).find("#commentlist li").last().hide().appendTo(l).fadeIn(600);a.fadeOut(300);d.removeAttr("disabled").filter("textarea").val("").focus();c++;b.html(c+" comment"+(1<c?"s":""))}})});return!1};$("#submit").click(function(a){a.preventDefault();
p()&&k()});$("#clearFields").click(function(a){a.preventDefault();e.removeClass("error").find("input,textarea").val("").eq(0).focus()});$(".link-to-comments").click(function(a){a.preventDefault();a=$("#comments-panel").offset().top;$(".sub-frame").eq(0).animate({scrollTop:a+"px"},Math.round(a/3),function(){setTimeout(function(){window.location.hash="#comments-panel"},1E3)})})},socialShare:function(){var f={facebook:{url:"https://www.facebook.com/sharer/sharer.php?u="},twitter:{url:"https://twitter.com/home?status=",
descriptionSeparator:":%20",width:"635",height:"430"},google:{url:"https://plus.google.com/share?url=",width:"560",height:"580"},pinterest:{url:"https://pinterest.com/pin/create/button/?url=",width:"1000",height:"600"}},g=window.location.href;$("a.share").click(function(d){d.preventDefault();d=$(this);var a=$.parseJSON($.trim(d.attr("data-share").replace(/\'/g,'"')));if(null!=a){var a=$.extend({on:"",media:"",description:""},a),h=a.on;d=$.extend({width:"600",height:"360",mediaSeparator:"&media=",
descriptionSeparator:"&description=",title:"Share"},f[h]);var l=e.$window.width(),b=e.$window.height(),c=parseInt(d.width),p=parseInt(d.height);l<c+30&&(c=l-30,d.width=c);b<p+60&&(p=b-60,d.height=p);l=Math.round((l-c)/2);b=Math.round((b-p)/2);a.description=encodeURI(a.description.replace(/\|/g,"'"));switch(h){case "pinterest":a=d.url+g+d.mediaSeparator+a.media+d.descriptionSeparator+a.description;break;case "twitter":a=d.url+a.description+d.descriptionSeparator+g;break;default:a=d.url+g}window.open(a,
d.title,"width="+d.width+", height="+d.height+",left="+l+",top="+b)}})},skechbook:function(){$(".sketchbook").each(function(){var a=$(this),b=a.find(">.sk-page"),c=0,e=b.length,d=$('<div class="sk-btn sk-btn-prev ready disabled" title="Previous sketch"></div>'),f=$('<div class="sk-btn sk-btn-next" title="Next sketch"><span>Turn the page</span></div>'),g=$('<div id="sketchbook-restart" class="button red" title="Start the Sketchbook from the beginning">Restart Sketchbook</div>'),h=!1,u=function(){var a,
b=document.createElement("fakeelement");transitions={transition:"transitionend",OTransition:"oTransitionEnd",MozTransition:"transitionend",WebkitTransition:"webkitTransitionEnd"};for(a in transitions)if(void 0!==b.style[a])return transitions[a]}(),D=!1,n=function(a){if(!D){var g=!1;if(c==e&&1==a||0==c&&-1==a)g=!0;if(!g){D=!0;if(1==a){var h=c-1;a=c;var l=c+1,x=b.eq(h),m=b.eq(a),q=b.eq(l);m.removeClass("sk-right sk-visible").addClass("sk-over sk-pos-right sk-right-to-center");l<=e&&q.addClass("sk-visible");
setTimeout(function(){m.removeClass("sk-pos-right").addClass("sk-pos-center sk-animated1")},100);var n=[function(){m.removeClass("sk-right-to-center sk-pos-center sk-animated1").addClass("sk-left-to-center sk-pos-left sk-animated2")},function(){0<h&&x.removeClass("sk-visible");m.removeClass("sk-over sk-left-to-center sk-pos-left sk-animated2").addClass("sk-left sk-visible").unbind(u);c++;d.removeClass("disabled");c>=e&&f.addClass("disabled");D=!1}],s=0}else h=c-2,a=c-1,l=c,x=b.eq(h),m=b.eq(a),q=b.eq(c),
0<h&&x.addClass("sk-visible"),m.removeClass("sk-left sk-visible").addClass("sk-over sk-pos-left sk-left-to-center"),setTimeout(function(){m.removeClass("sk-pos-left").addClass("sk-pos-center sk-animated1")},100),n=[function(){m.removeClass("sk-left-to-center sk-pos-center sk-animated1").addClass("sk-right-to-center sk-pos-right sk-animated2")},function(){l<=e&&q.removeClass("sk-visible");m.removeClass("sk-over sk-right-to-center sk-pos-right sk-animated2").addClass("sk-right sk-visible").unbind(u);
c--;f.removeClass("disabled");0>=c&&d.addClass("disabled");D=!1}],s=0;m.bind(u,function(){n[s]();s++})}}};a.append(d).append(g).append(f);d.click(function(){n(-1)});f.click(function(){n(1)}).hover(function(){h||(h=!0,f.addClass("ready").find("span").animate({opacity:0,right:"300%"},250,function(){$(this).hide()}))});g.click(function(){b.fadeOut(300,function(){b.removeClass("sk-left sk-visible").addClass("sk-right").eq(0).addClass("sk-visible");f.removeClass("disabled");d.addClass("disabled");c=0;
b.fadeIn(300)})});(function(){b.each(function(a){a=$(this).append('<div class="sk-shadow"></div>').find(".sk-face");a.eq(0).addClass("face-front");a.eq(1).addClass("face-back")}).addClass("sk-right").eq(0).addClass("sk-visible");a.addClass("rendered")})()});var e=$(".sketchbook-img"),g=e.length,d=0,a=function(){if(d<g){var a=e.eq(d),b=a.attr("srcwait");a.attr("src",b)}},h=function(){e.eq(d).siblings(".loading-sketch-banner").hide();++d;a()};e.load(h).error(h);a()},designList:function(){var f=["5a7880",
"5a8074","76805a","806c56","756a80"],g=-1,d=function(){var a="#"+f[++g];g=g>=f.length-1?-1:g;return a},a,h=null,l=300,b=!1,c=!1,p=0,k="object"===typeof document.attachEvent?!0:!1,v=$("#design-slider"),r=v.find(".d-slide").each(function(){$(this).css("background-color",d())}),y=r.length,u=$("#design-more,#footer-main"),D=v.parent(),n=0,B=$("#scroll-down"),w=function(){r.each(function(){var a=.5*(l-$(this).find(".d-slide-anim-ramp").height()),a=10>a?10:a;$(this).find(".d-slide-anim,.d-slide-text").css("top",
a+"px")})},C=function(){l=e.$window.height()-60;v.height(l);w()},z=function(d){if(!b&&0==p){var e=n+d;0<=e&&e<y&&(null!=h&&(B.fadeOut(200),h=null),b=!0,n=e,0<d?(r.filter(".prev").removeClass("prev"),r.eq(n-1).removeClass("current").addClass("prev animated"),r.eq(n).removeClass("next").addClass("current"),n+1<y&&r.eq(n+1).addClass("next")):(r.filter(".next").removeClass("next"),r.eq(n).removeClass("prev").addClass("current animated"),r.eq(n+1).removeClass("current").addClass("next"),0<=n-1&&r.eq(n-
1).addClass("prev")),setTimeout(function(){b=!1;r.filter(".animated").removeClass("animated");(c=n+1==y?!0:!1)?(u.show(),D.scrollTop(0)):u.hide()},800),a.find("span").removeClass("current").eq(n).addClass("current"))}};e.$html.scrollTop(0);r.eq(0).addClass("current");r.eq(1).addClass("next");v.fadeIn(400,function(){$("#design-loading").hide()});setTimeout(function(){C()},50);h=setTimeout(function(){B.fadeIn(400);h="waitHide"},5E3);C();(function(){for(var b='<div id="design-slider-control">',c="current",
e=0;e<y;e++)0<e&&(c=""),b+='<span class="'+c+'" rel="'+e+'"></span>';a=$(b+"</div>");a.appendTo(v)})();(function(){r.find("img").load(function(){w()});var a=function(){p=D.scrollTop()};e.$window.resize(function(){C();a()});var d=!1,f,h,g=!1,t=!1;v.on("mousedown",function(c){a();d||0!=p||b||k||(d=!0,f=c.pageY,0<=n-1&&(g=r.eq(n-1)),t=r.eq(n))});e.$window.on("mousemove",function(a){d&&(h=100*(a.pageY-f)/l,0<h&&g?(g.css("top",h-100+"%"),t.css("top","")):(g&&g.css("top",""),0>=h&&!c&&t.css("top",h+"%")))}).on("mouseup",
function(a){d&&(30<Math.abs(h)?(g&&g.css("top",""),t.css("top",""),t=g=d=!1,c&&0>=h||z(-1*Math.abs(h)/h)):(b=!0,0<h&&g?g.animate({top:"-100%"},200,function(){g.css("top","");b=t=g=d=!1}):0>=h&&t.animate({top:"0%"},200,function(){t.css("top","");b=t=g=d=!1})))});v.on("DOMMouseScroll",function(c){a();d||0!=p||b||z(0<c.originalEvent.detail?1:-1)}).on("mousewheel",function(c){a();d||0!=p||b||z(0>c.originalEvent.wheelDelta?1:-1)});var u=!1;e.$window.on("keydown",function(c){if(!(d||u||0!=p||b||k)){u=!0;
c=c.keyCode?c.keyCode:c.charCode;if(37==c||38==c)a(),z(-1);if(39==c||40==c)a(),z(1)}}).on("keyup",function(a){u&&(u=!1)})})()}};e.skillmeter=function(){var f=function(a,b,c,d,e){a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke();a.closePath()},g,d,a,h,l,b,c,p,k,v,r,y,u,w,n,B=null,G,C,z,x,m=null,q=null,A=null,s=null,t,I,H,E=["My Illustration skills","My Design skills","My skills for Traditional Artwork","Software I use","Technologies I know"],F=[[{label:"Digital\npainting",color:"rgba(255,0,0,",
val:100},{label:"Matte-painting",color:"rgba(255,120,0,",val:50},{label:"Fantasy\n& books",color:"rgba(222,167,0,",val:80},{label:"Characters",color:"rgba(58,165,0,",val:90},{label:"Concept Art",color:"rgba(0,162,255,",val:70},{label:"Speed-painting",color:"rgba(108,36,255,",val:60}],[{label:"Web Design",color:"rgba(0,150,255,",val:100},{label:"UX Analysis",color:"rgba(0,189,116,",val:60},{label:"Interactive\napps",color:"rgba(104,176,0,",val:75},{label:"Infographics",color:"rgba(223,184,0,",val:95},
{label:"3D modeling",color:"rgba(255,114,0,",val:50},{label:"Icons & logos",color:"rgba(255,24,0,",val:65},{label:"Advertising",color:"rgba(255,0,126,",val:75}],[{label:"Oil on canvas",color:"rgba(255,48,0,",val:100},{label:"Drawing",color:"rgba(58,165,0,",val:90},{label:"Watercolor",color:"rgba(0,144,255,",val:60},{label:"Pencils",color:"rgba(224,169,0,",val:40},{label:"Sketches",color:"rgba(255,107,27,",val:80}],[{label:"Adobe\nPhotoshop",color:"rgba(0,70,174,",val:100},{label:"Adobe\nIllustrator",
color:"rgba(255,180,0,",val:65},{label:"Krita",color:"rgba(210,0,255,",val:90},{label:"Blender 3D",color:"rgba(255,126,0,",val:45},{label:"SublimeText\n(for coding)",color:"rgba(47,168,0,",val:70}],[{label:"HTML5",color:"rgba(255,102,0,",val:90},{label:"CSS3",color:"rgba(0,162,255,",val:100},{label:"Javascript",color:"rgba(219,196,0,",val:80},{label:"JQuery",color:"rgba(0,95,238,",val:90},{label:"Wordpress",color:"rgba(0,126,179,",val:50},{label:"Web Mobile",color:"rgba(47,168,0,",val:75},{label:"GIT",
color:"rgba(159,0,241,",val:30}]];return{init:function(){g=document.getElementById("skill-meter");d=$(g);var b;if(b=null!=g)b=document.createElement("canvas"),b=!(!b.getContext||!b.getContext("2d"));if(b){y=$(".skill-meter-wrap");w=$(".skill-meter-arrow").show();n=0;u=$(".skill-meter-controls");b="";for(var c=0;c<F.length;c++)b+='<div data-ind="'+c+'" class="smc bubble"><span class="bubble-msg">'+E[c]+"</span></div>";u.html(b);a=g.getContext("2d");a.lineCap="round";v=new Image;v.src=baseTemplateURL+
"/img/skill-sprite.png";this.changeData(0).setEvents(this)}else d.html('<img style="display:block" src="'+baseTemplateURL+'/img/skillmeter-replace.png"/>')},onresize:function(){h=y.width();l=350;d.attr({width:h,height:l});I=660>h?5:500>h?4:20;m=20;q=35;A=h-20-20;s=l-35-155;H=t.length>I?I:t.length;G=Math.round(2*A/(H+1));z=Math.round(.5*G);x=Math.round(.25*G);C=.5*x;c=q+s;p=.01*s;this.draw();return this},changeData:function(a){n=a;n>=F.length&&(n=0);0>n&&(n=F.length-1);u.find(".smc").removeClass("current").eq(n).addClass("current");
t=F[n];this.onresize();return this},draw:function(){null!=r&&(clearInterval(r),r=null);for(var d=this,e=[],f=[],g=[],k=0;k<t.length;k++)e.push(!1),f.push(0),g.push(0);r=setInterval(function(){a.clearRect(0,0,h,l);d.drawBase();a.lineWidth=3;e[0]=!0;for(var k=0;k<H;k++)if(e[k]){a.strokeStyle=t[k].color+".6)";a.fillStyle=t[k].color+".4)";f[k]!=t[k].val&&(f[k]+=.05*(t[k].val-f[k]),f[k]=Math.round(100*f[k])/100,.1>t[k].val-f[k]&&(f[k]=t[k].val));d.drawCurve(k,f[k]);.5<f[k]/t[k].val&&"undefined"!=typeof e[k+
1]&&(e[k+1]=!0);1>g[k]&&(g[k]+=.02,a.globalAlpha=g[k]);a.drawImage(v,24*k,24*n,24,24,b-12,c+15,24,24);a.fillStyle="#333";a.textAlign="center";a.font="11px sans-serif";var m=a,p=b,q=c+56,s=t[k].label.split("\n");m.save();m.translate(p,q);for(i=0;i<s.length;i++)m.fillText(s[i],0,14*i);m.restore();a.globalAlpha=1}f[t.length-1]==t[t.length-1].val&&(clearInterval(r),r=null)},15)},drawCurve:function(d,e){0<e&&(k=Math.round(e*p),b=m+(d+1)*z,a.beginPath(),a.moveTo(b-z,c),a.quadraticCurveTo(b-z+C,c,b-x,c-
Math.round(.5*k)),a.quadraticCurveTo(b-C,c-k,b,c-k),a.quadraticCurveTo(b+C,c-k,b+x,c-Math.round(.5*k)),a.quadraticCurveTo(b+z-C,c,b+z,c),a.fill(),a.stroke(),a.closePath())},drawBase:function(){a.lineWidth=1;a.strokeStyle="#888";for(var d=0;d<t.length;d++)b=m+(d+1)*z,f(a,b,q-10,b,c+10);var e=Math.round(c/50);a.lineWidth=e;a.strokeStyle="#FFF";for(d=0;50>d;d+=2){var g=c-d*e;f(a,m,g,m+A,g)}a.lineWidth=1;a.strokeStyle="#DDD";f(a,m,q,m+A,q);f(a,m,q+.5*s,m+A,q+.5*s);f(a,m,q+s,m+A,q+s);a.strokeStyle="#999";
a.beginPath();a.moveTo(m+x,q+s+76);a.quadraticCurveTo(m+x,q+s+76+15,m+x+15,q+s+76+15);a.lineTo(h/2-15,q+s+76+15);a.quadraticCurveTo(h/2,q+s+76+15,h/2,q+s+76+30);a.quadraticCurveTo(h/2,q+s+76+15,h/2+15,q+s+76+15);a.lineTo(m+A-x-15,q+s+76+15);a.quadraticCurveTo(m+A-x,q+s+76+15,m+A-x,q+s+76);a.stroke();a.closePath();a.fillStyle="#999";a.font="10px sans-serif";a.textAlign="left";a.fillText("100%",m,q-4);a.fillText("50%",m,q+.5*s-4);a.textAlign="right";a.fillText("100%",m+A,q-4);a.fillText("50%",m+A,q+
.5*s-4);a.fillStyle="#777";a.font="italic 18px sans-serif";a.textAlign="center";a.fillText(E[n],h/2,q+s+76+50)},setEvents:function(a){e.$window.resize(function(){a.onresize()});u.find(".smc").click(function(){null!=B&&(clearInterval(B),B=null);var b=parseInt($(this).attr("data-ind"));b!=n&&a.changeData(b)});w.click(function(){null!=B&&(clearInterval(B),B=null);var b=parseInt($(this).attr("data-ind"));a.changeData(n+b)});B=setInterval(function(){a.changeData(n+1)},1E4);return this}}}();e.aboutme=function(){var f=
$(".about-me section"),g=$("#about-me-summary-content"),d=$(".about-tab"),a=$("#about-me-img-pablo"),h=$("#contact"),l=$("#contact-container"),b=!1,c=function(){var c=h.offset().top-e.$scroll.scrollTop();c<h.height()&&!b&&(a.addClass("blur"),b=!0);c>h.height()&&b&&(a.removeClass("blur"),b=!1)},p=function(){var a=e.$window.height()-60,b=Math.round((a-g.height())/2);f.css("min-height",a+60+"px");f.eq(0).css("min-height",a+"px");0>b&&(b=0);180<b&&(b=180);g.css("margin-top",b+"px");c();a=(h.height()-
l.height())/2-20;20>a&&(a=20);l.css("margin-top",a+"px")};e.$window.resize(function(){p()}).scroll(function(){c()});d.click(function(){var a=parseInt($(this).attr("data-ind")),a=Math.round(f.eq(a).offset().top);$("html,body").animate({scrollTop:a+"px"},Math.round(.8*e.$window.height()))});p();e.skillmeter.init();e.$html.scrollTop(0);-1!==window.location.hash.indexOf("contact")&&$(".about-tab.for-contact").click()};e.init=function(){e.$window=$(window);e.$html=$("html");e.$scroll=E?e.$window:e.$html;
e.$body=$("body");e.tryMobile();e.nicescroll();$(".post-navigation").each(function(){var e=$(this),g=e.find("a").length;4>g&&e.addClass("for-"+g)}).addClass("visible");e.socialShare();switch(pageID){case "home":e.home();break;case "illustration-list":e.illustrationList();break;case "illustration-post":e.illustrationPost();break;case "blog-list":e.blogList();break;case "blog-post":e.blogPost();break;case "design-post":e.designPost();break;case "sketch-list":e.skechbook();break;case "design-list":e.designList();
break;case "about-me":e.aboutme()}e.header()};$("document").ready(function(){e.init()})})();
<?php if(extension_loaded('zlib')){ob_end_flush();}?>