<?php if(extension_loaded('zlib')){ob_start('ob_gzhandler');} header("Content-type: text/javascript"); ?>
(function(){var F,C=navigator.userAgent.toLowerCase();/mozilla/.test(C)&&/webkit/.test(C);F=/webkit/.test(C);/opera/.test(C);/msie/.test(C);"undefined"===typeof pageID&&(pageID="all");var f={header:function(){var e=$("#site-navigation"),g=$(".aside-sidebar"),d=!1,a=!1,h=f.$scroll.scrollTop(),l=f.$scroll.scrollTop()-10,b=!1,c=function(){h=f.$scroll.scrollTop();l<h?(a&&(a=!1,e.removeClass("open"),g.addClass("close")),70<h&&!d&&(d=!0,e.addClass("fixed"),setTimeout(function(){e.addClass("animated")},
50)),70<h&&!b&&(b=!0,e.addClass("disableMenu"))):l>h&&(a||(a=!0,e.addClass("open"),g.removeClass("close")),2>h&&d&&(d=!1,e.removeClass("fixed").removeClass("animated")),b&&(b=!1,e.removeClass("disableMenu")));l=h};70<h&&g.addClass("close");c();f.$window.scroll(c)},contentSlider:function(){$(".content .slider").each(function(){var e=$(this).addClass("rendered"),g=e.find("img"),d=g.length,a=-1,h=0,l=$('<div class="slider-content"></div>'),b=$('<div class="slider-controls"></div>'),c=$(),p=!1,k=$('<div class="slider-arrow to-left"><span></span></div>'),
v=$('<div class="slider-arrow to-right"><span></span></div>'),r=function(){l.css("height",g.eq(a).height()+"px")},x=function(b,k){b==a||p||(k&&null!=u&&(clearInterval(u),u=null),p=!0,0>b&&(b=d-1),b>=d&&(b=0),h=a,a=b,g.eq(a).addClass("current"),g.eq(h).removeClass("current").addClass("post-current"),c.eq(a).addClass("current"),c.eq(h).removeClass("current"),r(),setTimeout(function(){g.removeClass("post-current");p=!1},790))},u=setInterval(function(){x(a+1,!1)},7E3);e.html("").append(l.append(g)).append(b).append(k).append(v);
for(e=0;e<d;e++)$('<span title="'+g.eq(e).attr("alt")+'" data-ind="'+e+'"></span>').appendTo(b).click(function(){x(parseInt($(this).attr("data-ind")),!0)});c=b.find("span");k.click(function(){x(a-1,!0)});v.click(function(){x(a+1,!0)});x(0);f.$window.resize(r)})},waitImgsForLoad:function(e,f,d){var a=d||!1;e=$(e);var h=e.length,l=0,b=!1,c=function(){l++;l>=h&&!b&&(b=!0,f())};0<h?e.each(function(){var b=$(this);b[0].complete?c():(b.load(function(){c()}),a||b.error(c))}):f()},nicescroll:function(){$.fn.niceScroll?
f.$html.niceScroll({cursoropacitymin:.5,cursorcolor:"#999",cursorborder:"none",cursorborderradius:"1px",cursorfixedheight:100}):f.$html.css("overflow","auto")},home:function(){f.$html.scrollTop(0);var e=846/476,g=$("#home-presentation"),d=$("#home-presentation-content"),a=$("#home-presentation-videocontainer"),h=$("#home-presentation-text"),l=$("#home-presentation-text-wrap"),b=1E3,c=function(){b=f.$window.height()-65;g.height(b);var k=g.width(),c="100%",d="0";k/b<e&&(d=b*e,c=d+"px",d=-.5*(d-k)+"px");
a.css({width:c,left:d});k=l.height();h.css({top:.5*(b-k)+"px"})},p=function(){var a=.5*(f.$scroll.scrollTop()-60),a=a>b?b:a;d.css("top",a+"px")};c();p();f.$window.resize(c).scroll(p);l.animate({opacity:1},600);$("#goto-last-work").click(function(a){a.preventDefault();a=$(this).attr("href");a=$(a).offset().top;$("html,body").animate({scrollTop:a+"px"},800)})},illustrationList:function(){var e=4,g="all",d=!0,a=$(".gallery").not(".gridding").addClass("gridding"),h=a.find("figure"),l=$(".gallery-menu a"),
b=function(){var b=f.$window.width();e=4;1400>b&&(e=3);820>b&&(e=2);500>b&&(e=1);var c=0,d=0,g=100/e,l=Math.round(a.width()/e);h.not(".hidden").each(function(){$(this).css({width:g+"%",height:l+"px",left:c+"%",top:d+"px"});c+=g;100<=c&&(c=0,d+=l)});a.height(d+l)},c=function(a,c){a!=g&&d&&(d=!1,"all"==a?h.removeClass("hidden"):"all"==g?h.not("."+a).addClass("hidden"):(h.filter("."+g).addClass("hidden"),h.filter("."+a).removeClass("hidden")),g=a,setTimeout(function(){d=!0},600),l.parent().removeClass("current"),
c.parent().addClass("current"));b()};(function(){var a=$(".illustration-thumb-img"),b=a.length,c=0,d=function(){if(c<b){var d=a.eq(c),e=d.attr("srcwait");d.attr("src",e)}},e=function(a){null!==a&&a.css("opacity","1");++c;d()};a.load(function(){e($(this))}).error(function(){e(null)});d()})();b();f.$window.resize(b);l.click(function(a){a.preventDefault();a=$(this);var b=a.text().toLowerCase().replace(/ /g,"-");-1!=b.indexOf("all-")&&(b="all");c(b,a)})},illustrationPost:function(){f.$html.scrollTop(0);
$(".post-navigation").addClass("visible");var e=$(".illustration-post-large-image figure"),g=e.find("img").eq(0),d=$(".illustration-post .summary"),a=$(".summary-content-col"),h=5E3,l=f.$window.height(),b=!1,c=function(){var b=1,c=f.$scroll.scrollTop();80>=c?b=1:80<c&&300>=c?b=1-(c-80)/220:300<c&&(b=0);a.css("opacity",b);300<c&&(b=c-300,c=h-l,b>c&&(b=0<c?c:0),e.css("top",-b+"px"))},p=function(){l=f.$window.height();h=b?g.height():l;d.height(h+300-50)},k=null;(function(){var a=$("#scroll-down"),b=
6,c=!1;k=setInterval(function(){b--;0==b&&(a.fadeIn(400),c=!0)},1E3);f.$window.scroll(function(){c&&(a.fadeOut(400),b=10,c=!1)});return this})();p();c();g[0].complete?(b=!0,p(),c()):g.load(function(){b=!0;p();c()});f.$window.resize(function(){p();c()}).scroll(function(){c();k&&(clearInterval(k),k=null)});var v=$(".wipSlider");0<v.length&&$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){v.wipSlider()});var r=!1;$("pre").not(".no-print").each(function(){var a=$(this).addClass("prettyprint");
a.text(a.html());r=!0});r&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");f.socialComments(".illustration-post-large-image img,.content img");f.commentValidation()},blogList:function(){},blogPost:function(){var e=$(".wipSlider");0<e.length&&$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){e.wipSlider()});var g=!1;$("pre").not(".no-print").each(function(){var d=$(this).addClass("prettyprint");d.text(d.html());g=!0});g&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");
f.socialComments(".content img");f.commentValidation()},designPost:function(){var e=$(".wipSlider");0<e.length&&$.getScript(baseTemplateURL+"/js/libs/jquery.wipSlider.min.js",function(){e.wipSlider()});var g=!1;$("pre").not(".no-print").each(function(){var d=$(this).addClass("prettyprint");d.text(d.html());g=!0});g&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert");f.socialComments(".content img");f.commentValidation()},socialComments:function(e){var g=$("#comment-tabs"),
d=function(){var a=window.comment_tab_width||750,d=window.location.href;$("#gplus-tab").html('<div class="g-comments" data-width="'+a+'" data-href="'+d+'" data-first_party_property="BLOGGER" data-view_type="FILTERED_POSTMOD">Loading Google+ Comments ...</div>');$("#fb-comments").html('<div class="fb-comments" data-width="'+a+'" data-href="'+d+'" data-num-posts="20" data-colorscheme="light" data-mobile="auto"></div>')},a=function(){$.getScript("//apis.google.com/js/plusone.js?callback=gpcb");$.getScript("//connect.facebook.net/en_US/all.js#xfbml=1",
function(){FB.init();FB.XFBML.parse()})};0<g.length&&(function(){g.each(function(){var a=$(this),d=a.find(".controls"),b=d.find("a"),c=a.find(".content-tab"),e="",f=function(a){var f=a.attr("href");f!=e&&(e=f,b.parent().removeClass("active"),a.parent().addClass("active"),d.removeClass("gplus-tab facebook-tab wordpress-tab").addClass(e.substr(1)),c.hide(),$(e).show())};f(b.eq(0));b.click(function(a){a.preventDefault();f($(this))})})}(),d(),f.waitImgsForLoad(e||"",function(){setTimeout(function(){a()},
50)}))},commentValidation:function(){var e=$("#commentform");$("#statusMessage").html("");var f=e.find("fieldset.validate");f.find("input,textarea").val("");var d=e.find("input[type=text],input[type=email],textarea").removeAttr("disabled"),a=$("#adding-comment"),h=$("#adding-comment-error"),l=$("#commentlist"),b=$("#commentlist-title"),c=l.find(">li").length,p=function(){var a=!0;f.each(function(){var b=$(this).removeClass("error"),c=b.find("input,textarea");b.attr("data-min");var d=c.val();3>d.length?
(a=!1,b.addClass("error"),c.focus()):b.hasClass("email")&&-1==d.search(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i)&&(a=!1,b.addClass("error"),c.focus())});return a},k=function(){var f=e.serialize(),g=e.attr("action");d.attr("disabled","true");h.hide();a.fadeIn(300,function(){$.ajax({type:"post",url:g,data:f,error:function(){a.hide();h.show();d.removeAttr("disabled")},success:function(e){$(e).find("#commentlist li").last().hide().appendTo(l).fadeIn(600);a.fadeOut(300);d.removeAttr("disabled").filter("textarea").val("").focus();
c++;b.html(c+" comment"+(1<c?"s":""))}})});return!1};$("#submit").click(function(a){a.preventDefault();p()&&k()});$("#clearFields").click(function(a){a.preventDefault();f.removeClass("error").find("input,textarea").val("").eq(0).focus()});$(".link-to-comments").click(function(a){a.preventDefault();a=$("#comments-panel").offset().top;$(".sub-frame").eq(0).animate({scrollTop:a+"px"},Math.round(a/3),function(){setTimeout(function(){window.location.hash="#comments-panel"},1E3)})})},socialShare:function(){var e=
{facebook:{url:"https://www.facebook.com/sharer/sharer.php?u="},twitter:{url:"https://twitter.com/home?status=",descriptionSeparator:":%20",width:"635",height:"430"},google:{url:"https://plus.google.com/share?url=",width:"560",height:"580"},pinterest:{url:"https://pinterest.com/pin/create/button/?url=",width:"1000",height:"600"}},g=window.location.href;$("a.share").click(function(d){d.preventDefault();d=$(this);var a=$.parseJSON($.trim(d.attr("data-share").replace(/\'/g,'"')));if(null!=a){var a=$.extend({on:"",
media:"",description:""},a),h=a.on;d=$.extend({width:"600",height:"360",mediaSeparator:"&media=",descriptionSeparator:"&description=",title:"Share"},e[h]);var l=f.$window.width(),b=f.$window.height(),c=parseInt(d.width),p=parseInt(d.height);l<c+30&&(c=l-30,d.width=c);b<p+60&&(p=b-60,d.height=p);l=Math.round((l-c)/2);b=Math.round((b-p)/2);a.description=encodeURI(a.description.replace(/\|/g,"'"));switch(h){case "pinterest":a=d.url+g+d.mediaSeparator+a.media+d.descriptionSeparator+a.description;break;
case "twitter":a=d.url+a.description+d.descriptionSeparator+g;break;default:a=d.url+g}window.open(a,d.title,"width="+d.width+", height="+d.height+",left="+l+",top="+b)}})},skechbook:function(){$(".sketchbook").each(function(){var a=$(this),b=a.find(">.sk-page"),c=0,d=b.length,e=$('<div class="sk-btn sk-btn-prev ready disabled" title="Previous sketch"></div>'),f=$('<div class="sk-btn sk-btn-next" title="Next sketch"><span>Turn the page</span></div>'),h=$('<div id="sketchbook-restart" class="button red" title="Start the Sketchbook from the beginning">Restart Sketchbook</div>'),
g=!1,u=function(){var a,b=document.createElement("fakeelement");transitions={transition:"transitionend",OTransition:"oTransitionEnd",MozTransition:"transitionend",WebkitTransition:"webkitTransitionEnd"};for(a in transitions)if(void 0!==b.style[a])return transitions[a]}(),A=!1,n=function(a){if(!A){var h=!1;if(c==d&&1==a||0==c&&-1==a)h=!0;if(!h){A=!0;if(1==a){var g=c-1;a=c;var l=c+1,w=b.eq(g),m=b.eq(a),q=b.eq(l);m.removeClass("sk-right sk-visible").addClass("sk-over sk-pos-right sk-right-to-center");
l<=d&&q.addClass("sk-visible");setTimeout(function(){m.removeClass("sk-pos-right").addClass("sk-pos-center sk-animated1")},100);var n=[function(){m.removeClass("sk-right-to-center sk-pos-center sk-animated1").addClass("sk-left-to-center sk-pos-left sk-animated2")},function(){0<g&&w.removeClass("sk-visible");m.removeClass("sk-over sk-left-to-center sk-pos-left sk-animated2").addClass("sk-left sk-visible").unbind(u);c++;e.removeClass("disabled");c>=d&&f.addClass("disabled");A=!1}],s=0}else g=c-2,a=
c-1,l=c,w=b.eq(g),m=b.eq(a),q=b.eq(c),0<g&&w.addClass("sk-visible"),m.removeClass("sk-left sk-visible").addClass("sk-over sk-pos-left sk-left-to-center"),setTimeout(function(){m.removeClass("sk-pos-left").addClass("sk-pos-center sk-animated1")},100),n=[function(){m.removeClass("sk-left-to-center sk-pos-center sk-animated1").addClass("sk-right-to-center sk-pos-right sk-animated2")},function(){l<=d&&q.removeClass("sk-visible");m.removeClass("sk-over sk-right-to-center sk-pos-right sk-animated2").addClass("sk-right sk-visible").unbind(u);
c--;f.removeClass("disabled");0>=c&&e.addClass("disabled");A=!1}],s=0;m.bind(u,function(){n[s]();s++})}}};a.append(e).append(h).append(f);e.click(function(){n(-1)});f.click(function(){n(1)}).hover(function(){g||(g=!0,f.addClass("ready").find("span").animate({opacity:0,right:"300%"},250,function(){$(this).hide()}))});h.click(function(){b.fadeOut(300,function(){b.removeClass("sk-left sk-visible").addClass("sk-right").eq(0).addClass("sk-visible");f.removeClass("disabled");e.addClass("disabled");c=0;
b.fadeIn(300)})});(function(){b.each(function(a){a=$(this).append('<div class="sk-shadow"></div>').find(".sk-face");a.eq(0).addClass("face-front");a.eq(1).addClass("face-back")}).addClass("sk-right").eq(0).addClass("sk-visible");a.addClass("rendered")})()});var e=$(".sketchbook-img"),f=e.length,d=0,a=function(){if(d<f){var a=e.eq(d),b=a.attr("srcwait");a.attr("src",b)}},h=function(){e.eq(d).siblings(".loading-sketch-banner").hide();++d;a()};e.load(h).error(h);a()},designList:function(){var e=["5a7880",
"5a8074","76805a","806c56","756a80"],g=-1,d=function(){var a="#"+e[++g];g=g>=e.length-1?-1:g;return a},a,h=null,l=300,b=!1,c=!1,p=0,k="object"===typeof document.attachEvent?!0:!1,v=$("#design-slider"),r=v.find(".d-slide").each(function(){$(this).css("background-color",d())}),x=r.length,u=$("#design-more,#footer-main"),A=v.parent(),n=0,B=$("#scroll-down"),E=function(){r.each(function(){var a=.5*(l-$(this).find(".d-slide-anim-ramp").height()),a=10>a?10:a;$(this).find(".d-slide-anim,.d-slide-text").css("top",
a+"px")})},D=function(){l=f.$window.height()-60;v.height(l);E()},y=function(d){if(!b&&0==p){var e=n+d;0<=e&&e<x&&(null!=h&&(B.fadeOut(200),h=null),b=!0,n=e,0<d?(r.filter(".prev").removeClass("prev"),r.eq(n-1).removeClass("current").addClass("prev animated"),r.eq(n).removeClass("next").addClass("current"),n+1<x&&r.eq(n+1).addClass("next")):(r.filter(".next").removeClass("next"),r.eq(n).removeClass("prev").addClass("current animated"),r.eq(n+1).removeClass("current").addClass("next"),0<=n-1&&r.eq(n-
1).addClass("prev")),setTimeout(function(){b=!1;r.filter(".animated").removeClass("animated");(c=n+1==x?!0:!1)?(u.show(),A.scrollTop(0)):u.hide()},800),a.find("span").removeClass("current").eq(n).addClass("current"))}};f.$html.scrollTop(0);r.eq(0).addClass("current");r.eq(1).addClass("next");v.fadeIn(400,function(){$("#design-loading").hide()});setTimeout(function(){D()},50);h=setTimeout(function(){B.fadeIn(400);h="waitHide"},5E3);D();(function(){for(var b='<div id="design-slider-control">',c="current",
d=0;d<x;d++)0<d&&(c=""),b+='<span class="'+c+'" rel="'+d+'"></span>';a=$(b+"</div>");a.appendTo(v)})();(function(){r.find("img").load(function(){E()});var a=function(){p=A.scrollTop()};f.$window.resize(function(){D();a()});var d=!1,e,g,h=!1,t=!1;v.on("mousedown",function(c){a();d||0!=p||b||k||(d=!0,e=c.pageY,0<=n-1&&(h=r.eq(n-1)),t=r.eq(n))});f.$window.on("mousemove",function(a){d&&(g=100*(a.pageY-e)/l,0<g&&h?(h.css("top",g-100+"%"),t.css("top","")):(h&&h.css("top",""),0>=g&&!c&&t.css("top",g+"%")))}).on("mouseup",
function(a){d&&(30<Math.abs(g)?(h&&h.css("top",""),t.css("top",""),t=h=d=!1,c&&0>=g||y(-1*Math.abs(g)/g)):(b=!0,0<g&&h?h.animate({top:"-100%"},200,function(){h.css("top","");b=t=h=d=!1}):0>=g&&t.animate({top:"0%"},200,function(){t.css("top","");b=t=h=d=!1})))});v.on("DOMMouseScroll",function(c){a();d||0!=p||b||y(0<c.originalEvent.detail?1:-1)}).on("mousewheel",function(c){a();d||0!=p||b||y(0>c.originalEvent.wheelDelta?1:-1)});var u=!1;f.$window.on("keydown",function(c){if(!(d||u||0!=p||b||k)){u=!0;
c=c.keyCode?c.keyCode:c.charCode;if(37==c||38==c)a(),y(-1);if(39==c||40==c)a(),y(1)}}).on("keyup",function(a){u&&(u=!1)})})()}};f.skillmeter=function(){var e=function(a,b,c,d,e){a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke();a.closePath()},g,d,a,h,l,b,c,p,k,v,r,x,u,A,n,B=null,E,D,y,w,m=null,q=null,z=null,s=null,t,C,H,F=["My Illustration skills","My Design skills","My skills for Traditional Artwork","Software I use","Technologies I know"],G=[[{label:"Digital\npainting",color:"rgba(255,0,0,",
val:100},{label:"Matte-painting",color:"rgba(255,120,0,",val:50},{label:"Fantasy\n& books",color:"rgba(222,167,0,",val:80},{label:"Characters",color:"rgba(58,165,0,",val:90},{label:"Concept Art",color:"rgba(0,162,255,",val:70},{label:"Speed-painting",color:"rgba(108,36,255,",val:60}],[{label:"Web Design",color:"rgba(0,150,255,",val:100},{label:"UX Analysis",color:"rgba(0,189,116,",val:60},{label:"Interactive\napps",color:"rgba(104,176,0,",val:75},{label:"Infographics",color:"rgba(223,184,0,",val:95},
{label:"3D modeling",color:"rgba(255,114,0,",val:50},{label:"Icons & logos",color:"rgba(255,24,0,",val:65},{label:"Advertising",color:"rgba(255,0,126,",val:75}],[{label:"Oil on canvas",color:"rgba(255,48,0,",val:100},{label:"Drawing",color:"rgba(58,165,0,",val:90},{label:"Watercolor",color:"rgba(0,144,255,",val:60},{label:"Pencils",color:"rgba(224,169,0,",val:40},{label:"Sketches",color:"rgba(255,107,27,",val:80}],[{label:"Adobe\nPhotoshop",color:"rgba(0,70,174,",val:100},{label:"Adobe\nIllustrator",
color:"rgba(255,180,0,",val:65},{label:"Krita",color:"rgba(210,0,255,",val:90},{label:"Blender 3D",color:"rgba(255,126,0,",val:45},{label:"SublimeText\n(for coding)",color:"rgba(47,168,0,",val:70}],[{label:"HTML5",color:"rgba(255,102,0,",val:90},{label:"CSS3",color:"rgba(0,162,255,",val:100},{label:"Javascript",color:"rgba(219,196,0,",val:80},{label:"JQuery",color:"rgba(0,95,238,",val:90},{label:"Wordpress",color:"rgba(0,126,179,",val:50},{label:"Web Mobile",color:"rgba(47,168,0,",val:75},{label:"GIT",
color:"rgba(159,0,241,",val:30}]];return{init:function(){g=document.getElementById("skill-meter");d=$(g);var b;if(b=null!=g)b=document.createElement("canvas"),b=!(!b.getContext||!b.getContext("2d"));if(b){x=$(".skill-meter-wrap");A=$(".skill-meter-arrow").show();n=0;u=$(".skill-meter-controls");b="";for(var c=0;c<G.length;c++)b+='<div data-ind="'+c+'" class="smc bubble"><span class="bubble-msg">'+F[c]+"</span></div>";u.html(b);a=g.getContext("2d");a.lineCap="round";v=new Image;v.src=baseTemplateURL+
"/img/skill-sprite.png";this.changeData(0).setEvents(this)}else d.html('<img style="display:block" src="'+baseTemplateURL+'/img/skillmeter-replace.png"/>')},onresize:function(){h=x.width();l=350;d.attr({width:h,height:l});C=660>h?5:500>h?4:20;m=20;q=35;z=h-20-20;s=l-35-155;H=t.length>C?C:t.length;E=Math.round(2*z/(H+1));y=Math.round(.5*E);w=Math.round(.25*E);D=.5*w;c=q+s;p=.01*s;this.draw();return this},changeData:function(a){n=a;n>=G.length&&(n=0);0>n&&(n=G.length-1);u.find(".smc").removeClass("current").eq(n).addClass("current");
t=G[n];this.onresize();return this},draw:function(){null!=r&&(clearInterval(r),r=null);for(var d=this,e=[],f=[],g=[],k=0;k<t.length;k++)e.push(!1),f.push(0),g.push(0);r=setInterval(function(){a.clearRect(0,0,h,l);d.drawBase();a.lineWidth=3;e[0]=!0;for(var k=0;k<H;k++)if(e[k]){a.strokeStyle=t[k].color+".6)";a.fillStyle=t[k].color+".4)";f[k]!=t[k].val&&(f[k]+=.05*(t[k].val-f[k]),f[k]=Math.round(100*f[k])/100,.1>t[k].val-f[k]&&(f[k]=t[k].val));d.drawCurve(k,f[k]);.5<f[k]/t[k].val&&"undefined"!=typeof e[k+
1]&&(e[k+1]=!0);1>g[k]&&(g[k]+=.02,a.globalAlpha=g[k]);a.drawImage(v,24*k,24*n,24,24,b-12,c+15,24,24);a.fillStyle="#333";a.textAlign="center";a.font="11px sans-serif";var m=a,p=b,q=c+56,s=t[k].label.split("\n");m.save();m.translate(p,q);for(i=0;i<s.length;i++)m.fillText(s[i],0,14*i);m.restore();a.globalAlpha=1}f[t.length-1]==t[t.length-1].val&&(clearInterval(r),r=null)},15)},drawCurve:function(d,e){0<e&&(k=Math.round(e*p),b=m+(d+1)*y,a.beginPath(),a.moveTo(b-y,c),a.quadraticCurveTo(b-y+D,c,b-w,c-
Math.round(.5*k)),a.quadraticCurveTo(b-D,c-k,b,c-k),a.quadraticCurveTo(b+D,c-k,b+w,c-Math.round(.5*k)),a.quadraticCurveTo(b+y-D,c,b+y,c),a.fill(),a.stroke(),a.closePath())},drawBase:function(){a.lineWidth=1;a.strokeStyle="#888";for(var d=0;d<t.length;d++)b=m+(d+1)*y,e(a,b,q-10,b,c+10);var f=Math.round(c/50);a.lineWidth=f;a.strokeStyle="#FFF";for(d=0;50>d;d+=2){var g=c-d*f;e(a,m,g,m+z,g)}a.lineWidth=1;a.strokeStyle="#DDD";e(a,m,q,m+z,q);e(a,m,q+.5*s,m+z,q+.5*s);e(a,m,q+s,m+z,q+s);a.strokeStyle="#999";
a.beginPath();a.moveTo(m+w,q+s+76);a.quadraticCurveTo(m+w,q+s+76+15,m+w+15,q+s+76+15);a.lineTo(h/2-15,q+s+76+15);a.quadraticCurveTo(h/2,q+s+76+15,h/2,q+s+76+30);a.quadraticCurveTo(h/2,q+s+76+15,h/2+15,q+s+76+15);a.lineTo(m+z-w-15,q+s+76+15);a.quadraticCurveTo(m+z-w,q+s+76+15,m+z-w,q+s+76);a.stroke();a.closePath();a.fillStyle="#999";a.font="10px sans-serif";a.textAlign="left";a.fillText("100%",m,q-4);a.fillText("50%",m,q+.5*s-4);a.textAlign="right";a.fillText("100%",m+z,q-4);a.fillText("50%",m+z,q+
.5*s-4);a.fillStyle="#777";a.font="italic 18px sans-serif";a.textAlign="center";a.fillText(F[n],h/2,q+s+76+50)},setEvents:function(a){f.$window.resize(function(){a.onresize()});u.find(".smc").click(function(){null!=B&&(clearInterval(B),B=null);var b=parseInt($(this).attr("data-ind"));b!=n&&a.changeData(b)});A.click(function(){null!=B&&(clearInterval(B),B=null);var b=parseInt($(this).attr("data-ind"));a.changeData(n+b)});B=setInterval(function(){a.changeData(n+1)},1E4);return this}}}();f.aboutme=function(){var e=
$(".about-me section"),g=$("#about-me-summary-content"),d=$(".about-tab"),a=$("#about-me-img-pablo"),h=$("#contact"),l=$("#contact-container"),b=!1,c=function(){var c=h.offset().top-f.$scroll.scrollTop();c<h.height()&&!b&&(a.addClass("blur"),b=!0);c>h.height()&&b&&(a.removeClass("blur"),b=!1)},p=function(){var a=f.$window.height()-60,b=Math.round((a-g.height())/2);e.css("min-height",a+60+"px");e.eq(0).css("min-height",a+"px");0>b&&(b=0);180<b&&(b=180);g.css("margin-top",b+"px");c();a=(h.height()-
l.height())/2-20;20>a&&(a=20);l.css("margin-top",a+"px")};f.$window.resize(function(){p()}).scroll(function(){c()});d.click(function(){var a=parseInt($(this).attr("data-ind")),a=Math.round(e.eq(a).offset().top);$("html,body").animate({scrollTop:a+"px"},Math.round(.8*f.$window.height()))});p();f.skillmeter.init();f.$html.scrollTop(0);-1!==window.location.hash.indexOf("contact")&&$(".about-tab.for-contact").click()};f.init=function(){f.$window=$(window);f.$html=$("html");f.$scroll=F?f.$window:f.$html;
f.$body=$("body");f.nicescroll();$(".post-navigation").each(function(){var e=$(this),f=e.find("a").length;4>f&&e.addClass("for-"+f)}).addClass("visible");f.socialShare();switch(pageID){case "home":f.home();break;case "illustration-list":f.illustrationList();break;case "illustration-post":f.illustrationPost();break;case "blog-list":f.blogList();break;case "blog-post":f.blogPost();break;case "design-post":f.designPost();break;case "sketch-list":f.skechbook();break;case "design-list":f.designList();
break;case "about-me":f.aboutme()}f.header()};$("document").ready(function(){f.init()})})();
<?php if(extension_loaded('zlib')){ob_end_flush();}?>